name: Build and publish the new version to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-package:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/thombashi/python-ci:3.11

    steps:
    - uses: actions/checkout@v4

    - run: make build

    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./dist/*

  publish-package:
    needs: build-package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/DateTimeRange
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: ./dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v2.1.1
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl

    - name: Generate a GitHub release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        files: dist/*
